### ISSUE TITLE
Screen flickers on 1920 × 980px screen 

### ISSUE THREAD

**Issue by adarshaacharya** [total-typescript/zod-tutorial#15]
Page : https://www.totaltypescript.com/tutorials/zod/optional/solution

some weird behavior on this page only, the screen flickers continuously on my large-resolution monitor but works fine for monitor with small resolution.
Screen Size: `1920px × 1080px`

I've attached video but unfortunately, my screen recorder couldn't capture the fps on which the screen is flickering.

https://user-images.githubusercontent.com/50266088/194393200-d6953aa6-e481-453e-af03-7a4f313c5f3e.mp4

**Comment by adarshaacharya** [comment]
can't figure out the exact reason but putting width < 100% for main content solves the issue.

![image](https://user-images.githubusercontent.com/50266088/194393606-a185fdc8-41f5-4360-a393-92b35ea950ef.png)

**Comment by joelhooks** [comment]
Thanks so much for the report!
