### ISSUE TITLE
fix: typo in the exercise title

### ISSUE THREAD

**Issue by AlixFachin** [total-typescript/zod-tutorial#17]
Hi there,

Thank you very much for such great tutorials.
One small thing - there is a typo I think on the tutorial environment. Not sure where to mention it, maybe in this repo.

I guess it should be "Extract a type from a Pa**r**ser Object"

<img width="281" alt="image" src="https://user-images.githubusercontent.com/78192415/201087300-20ef3bec-2025-469b-b8e8-f8457440d2cf.png">

Apologies if that's not the right place to mention this kind of things.
Thanks again for the amazing tutorial!

**Comment by mattpocock** [comment]
Done!
